import dotenv from "dotenv";
import { query } from "./db.js";

dotenv.config();

const category = {
  id: "upper-mustang",
  name: "Upper Mustang",
  description: null,
};

const topics = [
  {
    id: "temperature-weather",
    categoryId: "upper-mustang",
    title: "Temperature & Weather Changes",
    description: "Changes in climate, temperature, and weather patterns.",
  },
  {
    id: "water-scarcity-glacier",
    categoryId: "upper-mustang",
    title: "Water Scarcity & Glacier Decline",
    description: "Water resources and glacier-related changes.",
  },
  {
    id: "agriculture-livelihood",
    categoryId: "upper-mustang",
    title: "Agricultural & Livelihood",
    description: "Agriculture, livelihoods, and changing rural practices.",
  },
  {
    id: "pasture-rangeland",
    categoryId: "upper-mustang",
    title: "Pasture & Rangeland Degradation",
    description: "Pasture health, grazing, and rangeland decline.",
  },
  {
    id: "environmental-hazards",
    categoryId: "upper-mustang",
    title: "Environmental Hazards",
    description: "Natural hazards linked to climate change.",
  },
  {
    id: "cultural-architectural",
    categoryId: "upper-mustang",
    title: "Cultural & Architectural Threats",
    description: "Threats to culture, homes, and heritage.",
  },
  {
    id: "public-health",
    categoryId: "upper-mustang",
    title: "Public Health Risks",
    description: "Health risks emerging with climate shifts.",
  },
  {
    id: "socio-economic",
    categoryId: "upper-mustang",
    title: "Socio-economic Changes",
    description: "Economic and social shifts affecting communities.",
  },
  {
    id: "tsarang",
    categoryId: "upper-mustang",
    title: "Tsarang Village",
    description: "Key issues and adaptation in Tsarang.",
  },
  {
    id: "marang",
    categoryId: "upper-mustang",
    title: "Marang Village",
    description: "Key issues and adaptation in Marang.",
  },
  {
    id: "surkhang",
    categoryId: "upper-mustang",
    title: "Surkhang (Yaraghara) Village",
    description: "Key issues in Surkhang (Yaraghara).",
  },
  {
    id: "lo-manthang",
    categoryId: "upper-mustang",
    title: "Lo Manthang",
    description: "Key issues and adaptation in Lo Manthang.",
  },
  {
    id: "samjong",
    categoryId: "upper-mustang",
    title: "Samjong Village",
    description: "Key issues and adaptation in Samjong.",
  },
  {
    id: "dhee",
    categoryId: "upper-mustang",
    title: "Dhee Village",
    description: "Key issues and adaptation in Dhee.",
  },
];

const subtopics = [
  {
    id: "temp-rise",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Rising temperatures / Heat increasing",
    description: "Rising temperatures across Upper Mustang.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "warmer-winters",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Warmer winters reducing winter chill accumulation",
    description: "Warmer winters reduce winter chill accumulation.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "intense-rainfall",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Unpredictable and intense rainfall",
    description: "Unpredictable and intense rainfall events.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "snowfall-decline",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Dramatic decline in seasonal snowfall / Snowfall reduced or stopped",
    description: "Seasonal snowfall reduced or stopped in many areas.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "snowfall-overview",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "About snowfall",
    description: "Overview of snowfall patterns and changes.",
    id: "humidity-heritage",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Increased humidity affecting homes and heritage",
    description: "Humidity affecting homes and heritage sites.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "rainfall-unpredictable",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Rainfall unpredictable",
    description: "Rainfall patterns are increasingly unpredictable.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "seasonal-patterns-shift",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Snow/rain no longer follow seasonal patterns",
    description: "Snow and rain no longer follow seasonal patterns.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "mosquitoes-first-time",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Mosquitoes appearing for the first time in the mountains",
    description: "Mosquitoes appearing at high altitudes for the first time.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "reduced-snow-meltwater",
    categoryId: "upper-mustang",
    parentTopicId: "water-scarcity-glacier",
    title: "Reduced snowfall → Less meltwater → Lower spring recharge",
    description: "Reduced snowfall lowers meltwater and spring recharge.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "humidity-heritage",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Increased humidity affecting homes and heritage",
    description: "Humidity affecting homes and heritage sites.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "rainfall-unpredictable",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Rainfall unpredictable",
    description: "Rainfall patterns are increasingly unpredictable.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "seasonal-patterns-shift",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Snow/rain no longer follow seasonal patterns",
    description: "Snow and rain no longer follow seasonal patterns.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "mosquitoes-first-time",
    categoryId: "upper-mustang",
    parentTopicId: "temperature-weather",
    title: "Mosquitoes appearing for the first time in the mountains",
    description: "Mosquitoes appearing at high altitudes for the first time.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "reduced-snow-meltwater",
    categoryId: "upper-mustang",
    parentTopicId: "water-scarcity-glacier",
    title: "Reduced snowfall → Less meltwater → Lower spring recharge",
    description: "Reduced snowfall lowers meltwater and spring recharge.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "springs-drying",
    categoryId: "upper-mustang",
    parentTopicId: "water-scarcity-glacier",
    title: "Springs drying up in villages (Samjong, Dhee)",
    description: "Springs drying up across villages like Samjong and Dhee.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "water-households",
    categoryId: "upper-mustang",
    parentTopicId: "water-scarcity-glacier",
    title: "Water scarcity affecting households",
    description: "Household water access is declining.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "water-livestock",
    categoryId: "upper-mustang",
    parentTopicId: "water-scarcity-glacier",
    title: "Water scarcity affecting livestock",
    description: "Livestock face water scarcity challenges.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "water-irrigation",
    categoryId: "upper-mustang",
    parentTopicId: "water-scarcity-glacier",
    title: "Water scarcity affecting irrigation",
    description: "Irrigation systems are constrained by water scarcity.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "cropping-calendars",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Traditional cropping calendars no longer reliable",
    description: "Traditional cropping calendars are no longer reliable.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "shorter-growing",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Shorter growing seasons",
    description: "Growing seasons are shorter and more variable.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "pest-outbreaks",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Pest outbreaks (especially apple orchards)",
    description: "Pest outbreaks increasing, especially in apple orchards.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "apple-farming-livelihood",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Apple farming introduced as a new livelihood",
    description: "Apple farming introduced as a new income source.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "decline-traditional-crops-pests",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Decline in traditional crops (barley, buckwheat, beans) or pests attack increased",
    description: "Traditional crops declining with rising pest attacks.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "pesticide-chemical-use",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Increase in use of pesticides and chemicals",
    description: "Rising dependence on pesticides and chemicals.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "apple-pests",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Apple pests increasing",
    description: "Apple pests are increasing and damaging yields.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "reduced-soil-moisture",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Reduced soil moisture",
    description: "Soil moisture levels are decreasing.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "decline-traditional-crops",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Decline in traditional crops (barley, buckwheat, beans)",
    description:
      "Traditional crops like barley, buckwheat, and beans are declining.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "machines-replacing",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Machines replacing manual labor",
    description: "Mechanization is replacing manual farm labor.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "waste-generation",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Waste generation rising",
    description: "Waste generation is rising in farming and settlements.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "new-farming-displacement",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "New farming after displacement (Samjong, Dhee – positive changes)",
    description: "New farming practices emerging after displacement.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "drying-pastures",
    categoryId: "upper-mustang",
    parentTopicId: "pasture-rangeland",
    title: "Drying pastures",
    description: "Pastures are drying and losing resilience.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "grazing-shrinking",
    categoryId: "upper-mustang",
    parentTopicId: "pasture-rangeland",
    title: "Grazing areas shrinking",
    description: "Grazing areas are shrinking due to climate stress.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "grazing-lands-pests",
    categoryId: "upper-mustang",
    parentTopicId: "pasture-rangeland",
    title: "Decreasing grazing lands and pests increase",
    description: "Grazing lands shrinking alongside rising pest pressures.",
    id: "apple-pests",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Apple pests increasing",
    description: "Apple pests are increasing and damaging yields.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "reduced-soil-moisture",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Reduced soil moisture",
    description: "Soil moisture levels are decreasing.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "decline-traditional-crops",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Decline in traditional crops (barley, buckwheat, beans)",
    description:
      "Traditional crops like barley, buckwheat, and beans are declining.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "machines-replacing",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Machines replacing manual labor",
    description: "Mechanization is replacing manual farm labor.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "waste-generation",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "Waste generation rising",
    description: "Waste generation is rising in farming and settlements.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "new-farming-displacement",
    categoryId: "upper-mustang",
    parentTopicId: "agriculture-livelihood",
    title: "New farming after displacement (Samjong, Dhee – positive changes)",
    description: "New farming practices emerging after displacement.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "drying-pastures",
    categoryId: "upper-mustang",
    parentTopicId: "pasture-rangeland",
    title: "Drying pastures",
    description: "Pastures are drying and losing resilience.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "grazing-shrinking",
    categoryId: "upper-mustang",
    parentTopicId: "pasture-rangeland",
    title: "Grazing areas shrinking",
    description: "Grazing areas are shrinking due to climate stress.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "invasive-species",
    categoryId: "upper-mustang",
    parentTopicId: "pasture-rangeland",
    title: "Invasive species replacing native grasses",
    description: "Invasive species are replacing native grasses.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "fodder-quality",
    categoryId: "upper-mustang",
    parentTopicId: "pasture-rangeland",
    title: "Reduced fodder quality",
    description: "Fodder quality is declining.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "invasive-species",
    categoryId: "upper-mustang",
    parentTopicId: "pasture-rangeland",
    title: "Invasive species replacing native grasses",
    description: "Invasive species are replacing native grasses.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "fodder-quality",
    categoryId: "upper-mustang",
    parentTopicId: "pasture-rangeland",
    title: "Reduced fodder quality",
    description: "Fodder quality is declining.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "livestock-health",
    categoryId: "upper-mustang",
    parentTopicId: "pasture-rangeland",
    title: "Declining livestock health and productivity",
    description: "Livestock health and productivity are declining.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "landslides",
    categoryId: "upper-mustang",
    parentTopicId: "environmental-hazards",
    title: "Increased landslides",
    description: "Landslide risks are increasing.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "flash-floods",
    categoryId: "upper-mustang",
    parentTopicId: "environmental-hazards",
    title: "Flash floods",
    description: "Flash flood events are more frequent.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "river-overflow",
    categoryId: "upper-mustang",
    parentTopicId: "environmental-hazards",
    title: "River overflow during monsoon (Kaligandaki affecting Dhee)",
    description: "Kaligandaki overflow affects access and safety in Dhee.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "erosion-fields",
    categoryId: "upper-mustang",
    parentTopicId: "environmental-hazards",
    title: "Soil erosion damaging fields",
    description: "Soil erosion damages agricultural fields.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "erosion-canals",
    categoryId: "upper-mustang",
    parentTopicId: "environmental-hazards",
    title: "Soil erosion damaging irrigation canals",
    description: "Soil erosion disrupts irrigation canals.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "mud-houses",
    categoryId: "upper-mustang",
    parentTopicId: "cultural-architectural",
    title: "Traditional mud houses weakened by moisture and heat",
    description: "Traditional mud houses are weakened by moisture and heat.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "heritage-deteriorating",
    categoryId: "upper-mustang",
    parentTopicId: "cultural-architectural",
    title: "Religious heritage (monasteries, murals) deteriorating",
    description:
      "Religious heritage like monasteries and murals is deteriorating.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "food-culture",
    categoryId: "upper-mustang",
    parentTopicId: "cultural-architectural",
    title: "Changing diets causing loss of food culture",
    description: "Changing diets are causing loss of food culture.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "mosquitoes-high-altitude",
    categoryId: "upper-mustang",
    parentTopicId: "public-health",
    title: "Emergence of mosquitoes at high altitude",
    description: "Mosquitoes emerging at high altitude.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "poor-water-quality",
    categoryId: "upper-mustang",
    parentTopicId: "public-health",
    title: "Poor water quality due to erosion",
    description: "Water quality declines due to erosion.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "unhealthy-indoors",
    categoryId: "upper-mustang",
    parentTopicId: "public-health",
    title: "Increased humidity causing unhealthy indoor conditions",
    description: "Humidity leads to unhealthy indoor conditions.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "tourism-shifting",
    categoryId: "upper-mustang",
    parentTopicId: "socio-economic",
    title: "Tourism patterns shifting",
    description: "Tourism patterns are shifting with climate change.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "modernization-traditions",
    categoryId: "upper-mustang",
    parentTopicId: "socio-economic",
    title: "Modernization replacing traditional practices",
    description: "Modernization is replacing traditional practices.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "migration-displacement",
    categoryId: "upper-mustang",
    parentTopicId: "socio-economic",
    title: "Migration and displacement (Samjong, Dhee)",
    description: "Migration and displacement affecting villages.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "tourism-decreasing",
    categoryId: "upper-mustang",
    parentTopicId: "socio-economic",
    title: "Tourism decreasing in some areas (e.g., Dhee)",
    description: "Tourism is decreasing in some areas such as Dhee.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "displacement-challenges",
    categoryId: "upper-mustang",
    parentTopicId: "socio-economic",
    title: "Displacement creating both benefits and challenges",
    description: "Displacement creates benefits and challenges.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "waste-management",
    categoryId: "upper-mustang",
    parentTopicId: "socio-economic",
    title: "Waste management issues increasing",
    description: "Waste management issues are increasing.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "tsarang-water-seepage",
    categoryId: "upper-mustang",
    parentTopicId: "tsarang",
    title: "Water seepage damaging mud homes",
    description: "Water seepage is damaging traditional mud homes.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "tsarang-humidity",
    categoryId: "upper-mustang",
    parentTopicId: "tsarang",
    title: "Rainfall no longer seasonal; rising humidity",
    description: "Non-seasonal rainfall and rising humidity.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "tsarang-pasture",
    categoryId: "upper-mustang",
    parentTopicId: "tsarang",
    title: "Pasture shrinking due to invasive species",
    description: "Pasture shrinking due to invasive species.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "tsarang-crop-yields",
    categoryId: "upper-mustang",
    parentTopicId: "tsarang",
    title: "Lower crop yields and irregular seasons",
    description: "Lower crop yields and irregular seasons.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "tsarang-mosquitoes",
    categoryId: "upper-mustang",
    parentTopicId: "tsarang",
    title: "Mosquitoes emerging for the first time",
    description: "Mosquitoes emerging for the first time.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "tsarang-landslides",
    categoryId: "upper-mustang",
    parentTopicId: "tsarang",
    title: "Increased landslide risks",
    description: "Landslide risks increasing around the village.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "tsarang-crops",
    categoryId: "upper-mustang",
    parentTopicId: "tsarang",
    title: "Disappearance of traditional crops",
    description: "Traditional crops are disappearing.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "tsarang-livestock",
    categoryId: "upper-mustang",
    parentTopicId: "tsarang",
    title: "Declining livestock productivity",
    description: "Livestock productivity is declining.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "tsarang-new-crops",
    categoryId: "upper-mustang",
    parentTopicId: "tsarang",
    title: "New crops (spinach, radish) growing better in warmer springs",
    description: "New crops growing better in warmer springs.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "marang-snowfall",
    categoryId: "upper-mustang",
    parentTopicId: "marang",
    title: "Reduced snowfall reducing water availability",
    description: "Reduced snowfall reduces water availability.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "marang-weather",
    categoryId: "upper-mustang",
    parentTopicId: "marang",
    title: "Erratic weather disrupting crop calendars",
    description: "Erratic weather disrupts crop calendars.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "marang-apple-pests",
    categoryId: "upper-mustang",
    parentTopicId: "marang",
    title: "Apple pests increasing",
    description: "Apple pests are increasing in Marang.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "marang-crop-failures",
    categoryId: "upper-mustang",
    parentTopicId: "marang",
    title: "Frequent crop failures",
    description: "Crop failures are increasingly frequent.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "marang-diversification",
    categoryId: "upper-mustang",
    parentTopicId: "marang",
    title: "Leafy green and legume diversification supporting food security",
    description: "Diversifying crops supports food security.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "surkhang-erosion",
    categoryId: "upper-mustang",
    parentTopicId: "surkhang",
    title: "Soil erosion collapsing terraces",
    description: "Soil erosion is collapsing terraces.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "surkhang-canals",
    categoryId: "upper-mustang",
    parentTopicId: "surkhang",
    title: "Irrigation canals blocked by debris",
    description: "Irrigation canals are blocked by debris.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "surkhang-pasture",
    categoryId: "upper-mustang",
    parentTopicId: "surkhang",
    title: "Pasturelands degrading",
    description: "Pasturelands are degrading.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "surkhang-yields",
    categoryId: "upper-mustang",
    parentTopicId: "surkhang",
    title: "Unpredictable rain/snow lowering apple and grain yields",
    description: "Unpredictable rain/snow lowers apple and grain yields.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "lo-heritage",
    categoryId: "upper-mustang",
    parentTopicId: "lo-manthang",
    title: "Moisture damage to monasteries and cultural heritage",
    description: "Moisture damages monasteries and cultural heritage.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "lo-waste",
    categoryId: "upper-mustang",
    parentTopicId: "lo-manthang",
    title: "Poor waste management due to tourism",
    description: "Poor waste management due to tourism pressure.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "lo-overgrazed",
    categoryId: "upper-mustang",
    parentTopicId: "lo-manthang",
    title: "Overgrazed high-altitude pastures",
    description: "High-altitude pastures are overgrazed.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "lo-rainfall",
    categoryId: "upper-mustang",
    parentTopicId: "lo-manthang",
    title: "Erratic rainfall harming barley and buckwheat",
    description: "Erratic rainfall harms barley and buckwheat.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "lo-tourist-season",
    categoryId: "upper-mustang",
    parentTopicId: "lo-manthang",
    title: "Longer tourist season",
    description: "Longer tourist season benefits local livelihoods.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "lo-homestays",
    categoryId: "upper-mustang",
    parentTopicId: "lo-manthang",
    title: "Women-run homestays benefiting livelihoods",
    description: "Women-run homestays improving livelihoods.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "samjong-water",
    categoryId: "upper-mustang",
    parentTopicId: "samjong",
    title: "Severe water scarcity forcing village relocation",
    description: "Severe water scarcity forced relocation.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "samjong-identity",
    categoryId: "upper-mustang",
    parentTopicId: "samjong",
    title: "Loss of ancestral land and cultural identity",
    description: "Loss of ancestral land and cultural identity.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "samjong-soils",
    categoryId: "upper-mustang",
    parentTopicId: "samjong",
    title: "Difficulty adjusting to new soils and climate",
    description: "Difficulty adjusting to new soils and climate.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "samjong-strain",
    categoryId: "upper-mustang",
    parentTopicId: "samjong",
    title: "Emotional and psychological strain (especially elders)",
    description: "Emotional and psychological strain, especially among elders.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "samjong-water-facilities",
    categoryId: "upper-mustang",
    parentTopicId: "samjong",
    title: "Improved water facilities in new location",
    description: "Improved water facilities in the new location.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "samjong-apple-farming",
    categoryId: "upper-mustang",
    parentTopicId: "samjong",
    title: "Apple farming introduced as a new livelihood",
    description: "Apple farming introduced as a new livelihood.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "dhee-water-shortages",
    categoryId: "upper-mustang",
    parentTopicId: "dhee",
    title: "Water shortages leading to full relocation",
    description: "Water shortages led to full relocation.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "dhee-crop-collapse",
    categoryId: "upper-mustang",
    parentTopicId: "dhee",
    title: "Pre-relocation crop collapse and food insecurity",
    description: "Crop collapse and food insecurity before relocation.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "dhee-erosion-water",
    categoryId: "upper-mustang",
    parentTopicId: "dhee",
    title: "Soil erosion contaminating water",
    description: "Soil erosion contaminates water sources.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "dhee-orchards",
    categoryId: "upper-mustang",
    parentTopicId: "dhee",
    title: "Apple orchards showing climate-induced disease",
    description: "Apple orchards show climate-induced disease.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "dhee-monsoon-access",
    categoryId: "upper-mustang",
    parentTopicId: "dhee",
    title: "Difficult monsoon access due to Kaligandaki overflow",
    description: "Monsoon access difficult due to Kaligandaki overflow.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "dhee-vegetable-gardens",
    categoryId: "upper-mustang",
    parentTopicId: "dhee",
    title: "Irrigated vegetable gardens improving income and nutrition",
    description: "Irrigated vegetable gardens improve income and nutrition.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
  {
    id: "dhee-rituals",
    categoryId: "upper-mustang",
    parentTopicId: "dhee",
    title: "Community rituals practiced to protect orchards",
    description: "Community rituals practiced to protect orchards.",
    animatedDocsKey: "upperMustangClimateDocsData",
  },
];

async function main() {
  try {
    await query("BEGIN");

    await query(
      `INSERT INTO categories (id, name, description)
       VALUES ($1, $2, $3)
       ON CONFLICT (id) DO UPDATE
         SET name = EXCLUDED.name,
             description = EXCLUDED.description`,
      [category.id, category.name, category.description]
    );

    for (const topic of topics) {
      await query(
        `INSERT INTO topics (id, category_id, name, description)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT (id) DO UPDATE
           SET name = EXCLUDED.name,
               description = EXCLUDED.description,
               category_id = EXCLUDED.category_id`,
        [topic.id, topic.categoryId, topic.title, topic.description]
      );
    }

    for (const subtopic of subtopics) {
      await query(
        `INSERT INTO subtopics (id, topic_id, name, description, has_animated_docs)
         VALUES ($1, $2, $3, $4, $5)
         ON CONFLICT (id) DO UPDATE
           SET name = EXCLUDED.name,
               description = EXCLUDED.description,
               topic_id = EXCLUDED.topic_id,
               has_animated_docs = EXCLUDED.has_animated_docs`,
        [
          subtopic.id,
          subtopic.parentTopicId,
          subtopic.title,
          subtopic.description,
          Boolean(subtopic.animatedDocsKey),
        ]
      );
    }

    await query("COMMIT");
    console.log(`Seeded ${topics.length} topics and ${subtopics.length} subtopics.`);
  } catch (error) {
    await query("ROLLBACK");
    console.error("Failed to seed taxonomy:", error.message || error);
    process.exitCode = 1;
  }
}

main();
